services:
  postgres:
    image: postgres:16-alpine
    container_name: dav_kata_rastreo_envios_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./insumos/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dav_kata_rastreo_envios"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
